jobs:
  autosquash-crowdin:
    if: github.event.pull_request.head.repo.full_name == 'Slimefun/Slimefun4'
    name: Auto squash (Crowdin)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        MERGE_COMMIT_MESSAGE: '[CI skip] New locale updates from Crowdin'
        MERGE_DELETE_BRANCH: true
        MERGE_FORKS: false
        MERGE_LABELS: "\U0001F4C4 Translations Update"
        MERGE_METHOD: squash
        UPDATE_RETRIES: 0
      name: Auto squash
      uses: pascalgn/automerge-action@v0.16.2
  autosquash-renovate:
    if: github.event.pull_request.head.repo.full_name == 'Slimefun/Slimefun4'
    name: Auto squash (Renovate)
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        MERGE_COMMIT_MESSAGE: '[CI skip] ${{ github.event.pull_request.title }}'
        MERGE_DELETE_BRANCH: true
        MERGE_FORKS: false
        MERGE_LABELS: "\U0001F6A8 Dependency Update"
        MERGE_METHOD: squash
        UPDATE_RETRIES: 0
      name: Auto squash
      uses: pascalgn/automerge-action@v0.16.2
name: Auto squash pull requests
on:
  repository_dispatch:
    types: trigger-ga___auto-squash.yml
