jobs:
  auto-approve:
    if: github.event.pull_request.head.repo.full_name == 'Slimefun/Slimefun4'
    name: Auto approve Pull Request
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.actor == 'TheBusyBot' || github.actor == 'renovate[bot]'
      name: Approve via actions
      uses: hmarr/auto-approve-action@v4.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
name: Auto approve
on:
  repository_dispatch:
    types: trigger-ga___auto-approve.yml
permissions:
  contents: read
