jobs:
  comment:
    if: "contains(github.event.issue.labels.*.name, '\U0001F41E Bug Report') == false\
      \ && contains(github.event.issue.labels.*.name, 'Hacktoberfest') == false"
    name: Invalid Issues
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Close Issue
      uses: maxkomarychev/octions/octions/issues/update@master
      with:
        issue_number: ${{ github.event.issue.number }}
        state: closed
        token: ${{ secrets.ACCESS_TOKEN }}
    - continue-on-error: true
      name: Add invalid label
      uses: maxkomarychev/octions/octions/issues/add-labels@master
      with:
        issue_number: ${{ github.event.issue.number }}
        labels: invalid
        token: ${{ secrets.ACCESS_TOKEN }}
    - continue-on-error: true
      name: Create a comment
      uses: maxkomarychev/octions/octions/issues/create-comment@master
      with:
        body: 'Your issue seems to be missing our template.

          [Click here to create a bug report](https://github.com/Slimefun/Slimefun4/issues/new/choose)


          Please remember that this Bug Tracker is exclusively reserved for Bug reports,
          any other form

          of discussion, like suggestions or questions should be posted on our discord
          server (You can find a link [on our main page](https://github.com/Slimefun/Slimefun4#discord)).'
        issue_number: ${{ github.event.issue.number }}
        token: ${{ secrets.ACCESS_TOKEN }}
name: Close invalid Issue
on:
  repository_dispatch:
    types: trigger-ga___close-invalid-issues.yml
