jobs:
  report:
    if: github.repository == 'Slimefun/Slimefun4'
    name: Discord Webhook
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4.1.1
    - continue-on-error: true
      name: Set up Java JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        architecture: x64
        distribution: adopt
        java-package: jdk
        java-version: '17'
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: Run Discord Webhook
      uses: baked-libs/discord-webhook@1.5.1
      with:
        id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
name: Discord Webhook
on:
  repository_dispatch:
    types: trigger-ga___discord-webhook.yml
permissions:
  contents: read
