jobs:
  comment:
    if: contains(github.event.comment.body, 'Duplicate of ')
    name: Mark Issue as duplicate
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Add label to the Issue
      uses: maxkomarychev/octions/octions/issues/add-labels@master
      with:
        issue_number: ${{ github.event.issue.number }}
        labels: "\U0001F6A9 Duplicate"
        token: ${{ secrets.ACCESS_TOKEN }}
name: Mark Issue as duplicate
on:
  repository_dispatch:
    types: trigger-ga___duplicates.yml
permissions:
  contents: read
  issues: write
