jobs:
  e2e-testing:
    name: End to End Testing
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4.0.0
      with:
        architecture: x64
        distribution: temurin
        java-package: jdk
        java-version: ${{ matrix.javaVersion }}
    - continue-on-error: true
      name: Setup server
      run: 'echo ''eula=true'' > eula.txt

        mkdir plugins

        '
    - continue-on-error: true
      name: Download ${{ matrix.mcVersion }} Paper
      run: "VERSION=\"${{ matrix.mcVersion }}\"\nif [ \"$VERSION\" == \"latest\" ];\
        \ then\n  VERSION=$(curl https://api.papermc.io/v2/projects/paper/ -s | jq\
        \ -r '.versions[-1]')\nfi\n\nBUILD_JAR=$(curl -s \"https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds\"\
        \ \\\n  | jq '.builds[-1] | \"\\(.build) \\(.downloads.application.name)\"\
        ' -r)\nBUILD=$(echo \"$BUILD_JAR\" | awk '{print $1}')\nJAR_FILE=$(echo \"\
        $BUILD_JAR\" | awk '{print $2}')\n\necho \"Downloading... https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/$JAR_FILE\"\
        \ncurl -o paper.jar \\\n  \"https://api.papermc.io/v2/projects/paper/versions/$VERSION/builds/$BUILD/downloads/$JAR_FILE\"\
        \n"
    - continue-on-error: true
      name: Download Slimefun
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: plugins/
    - continue-on-error: true
      name: Download e2e-tester
      run: 'curl -o e2e-tester.jar https://preview-builds.walshy.dev/download/e2e-tester/main/latest

        mv e2e-tester.jar plugins/e2e-tester.jar

        '
    - continue-on-error: true
      name: Run server
      run: 'java -jar paper.jar --nogui

        '
    strategy:
      matrix:
        include:
        - javaVersion: '16'
          mcVersion: 1.16.5
        - javaVersion: '17'
          mcVersion: 1.17.1
        - javaVersion: '18'
          mcVersion: 1.18.2
        - javaVersion: '19'
          mcVersion: 1.19.4
        - javaVersion: '20'
          mcVersion: latest
    timeout-minutes: 5
name: End to End Testing
on:
  repository_dispatch:
    types: trigger-ga___e2e-testing.yml
