jobs:
  validate:
    name: Validate JSON
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      env:
        INPUT_JSONS: src/main/resources/wiki.json
        INPUT_SCHEMA: .github/configs/wiki-schema.json
      name: Validate wiki.json
      uses: docker://orrosenblatt/validate-json-action:latest@sha256:02370758b8b199e0477da11ecfdd498c75c561685056b5c31b925a4ab95df7f4
name: Validate JSON
on:
  repository_dispatch:
    types: trigger-ga___json-validator.yml
permissions:
  contents: read
