jobs:
  validate:
    if: github.repository == 'Slimefun/Slimefun4'
    name: Check for merge conflicts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: mschilde/auto-label-merge-conflicts@master
      with:
        CONFLICT_LABEL_NAME: "\u26A1 Merge Conflicts"
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
name: Merge Conflicts
on:
  repository_dispatch:
    types: trigger-ga___merge-conflicts.yml
permissions:
  contents: read
  pull-requests: write
