jobs:
  publish:
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    name: Upload build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        architecture: x64
        distribution: adopt
        java-package: jdk
        java-version: '17'
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package
    - continue-on-error: true
      name: Upload to Blob Builds
      uses: WalshyDev/blob-builds/gh-action@f3da5ce7b7e2b70eb963e0c0014677b3d78c10fa
      with:
        apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
        file: ./target/Slimefun v4.9-UNOFFICIAL.jar
        project: Slimefun4
        releaseChannel: ${{ github.ref == 'refs/heads/master' && 'Dev' || 'RC' }}
        releaseNotes: ${{ github.event.head_commit.message }}
name: Publish build
on:
  repository_dispatch:
    types: trigger-ga___publish-build.yml
