jobs:
  scan:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    name: SonarCloud Scanner
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4.0.0
      with:
        architecture: x64
        distribution: adopt
        java-package: jdk
        java-version: '17'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache Maven packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      if: ${{ env.SONAR_TOKEN != 0 }}
      name: SonarCloud analysis
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
name: SonarCloud Scanner
on:
  repository_dispatch:
    types: trigger-ga___sonarcloud.yml
permissions:
  contents: read
